---
ID: "9e74dddc-1ba2-42fc-9ee2-dbc2221a0cdf"
Parent: "2fbcc456-3f7b-44b1-be81-505dd9a57fa7"
Template: "f62b4cd7-754c-4461-810f-2b6bd2c92a0d"
Path: /sitecore/client/Your Apps/Feature/SuperScripts/Dashboard/Script Library 2/Script 1/PageSettings/TabControl/Manage FXM functions/PageSettings/EditPageMatcherTabControl/Profiles
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 75
- ID: "deab3795-056f-4421-adf0-758844461b72"
  Hint: Placeholder Name
  Value: Profile
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          ds="{D4C1DA49-F5DB-4912-B75A-BFC8AAF161B4}"
          id="{79BD52E6-BA2F-421C-AC7E-622D636898C8}"
          par="Id=DeployedProfileCardsDataSource"
          uid="{3CD36AC9-AB61-4413-B6A9-5DA99C12FCE6}" />
        <r
          ds="{8EEA6694-1822-4850-8791-A4860AFE6ED1}"
          id="{442BD093-FBAD-4E36-BC08-489E16C82D08}"
          par="Id=ProfilesExpander&amp;IsCollapsible=0"
          uid="{E35A8DB4-1BEA-4A60-9B04-4A9D1D4EC84B}" />
        <r
          id="{F6C9F461-FCAF-47DC-AA01-C8C64C2EFFB8}"
          par="Id=ProfilesContentBorder&amp;UsePadding=1"
          ph="ProfilesExpander.Body"
          uid="{EC3B0852-5389-4400-B5AE-C43358BA7EBB}" />
        <r
          ds="{557D396B-D976-4B35-83FD-99C9CEE231FA}"
          id="{7717EB6C-9F90-4C58-826D-5E87722A0318}"
          par="Id=IntroText"
          ph="ProfilesContentBorder.Content"
          uid="{5CA5FFF6-53F3-495E-92BE-3E5DBA872D36}" />
        <r
          id="{1F36F9E6-CF70-430B-AA76-239CC08174A3}"
          par="AddButtonDataSource=%7b734D7323-70FD-4A4A-9B79-32D3A35B7AD9%7d&amp;RemoveButtonDataSource=%7bCD07DECF-4BEB-419A-B110-9D0A2392F3B5%7d&amp;Id=PageMatcherProfilesAnalyticsItemPicker&amp;Items=%7bBinding+DeployedProfileCardsDataSource.items%7d&amp;SelectedItemsLabelDataSource=%7bEBD27FB5-7232-4121-B1F9-71BCC203BFFC%7d&amp;AvailableItemsLabelDataSource=%7bF61AFE69-A0CD-4EF0-91D0-0EBB98822B16%7d&amp;Padding=1"
          ph="ProfilesContentBorder.Content"
          uid="{7C85DCE4-52AD-42C8-A419-6AAA741D8A71}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140605T142223Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9848f5b4-6d2c-4c87-adf9-7b665b33add3"
    - ID: "aea872fb-aa91-4d1a-b877-3ca6fbbb4fd4"
      Hint: Header
      Value: Profile
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210306T050308Z
